### ISSUE TITLE
Invariant failed: REACT_APP_DEVNET_FAUCET_BTC not found in assets in views/faucet

### ISSUE THREAD

**Issue by brown2243** [Friktion-Labs/frontend#1]
Hi!!!
i got failed to start in my local!
would you let me know what env and value i should set for project?

![image](https://user-images.githubusercontent.com/66369443/192143050-b6187217-cebd-4e28-a614-aaec44353cfb.png)

**Comment by jasonchitla** [comment]
add this to your .env file:
REACT_APP_DEVNET_FAUCET_BTC=97z3NzcDxqRMyE7F73PuHEmAbA72S7eDopjhe7GTymTk
REACT_APP_DEVNET_FAUCET_USDC=GPGFfX1cvfeXDaSd1MaYepxuPU6gvWqt8kq7P9pVvLRP

**Comment by brown2243** [comment]
Tks for your support!!!
